return {
  -- "williamboman/mason-lspconfig.nvim",
  -- dependencies = {
  --   "williamboman/mason.nvim",
  --   "WhoIsSethDaniel/mason-tool-installer.nvim",
  -- },
  -- config = function()
  --   local mason_lspconfig = require("mason-lspconfig")
  --   local mason_tool_installer = require("mason-tool-installer")
  --
  --   mason_lspconfig.setup({
  --     ensure_installed = {
  --       "ts_ls",
  --       "html",
  --       "cssls",
  --       "svelte",
  --       "lua_ls",
  --       "graphql",
  --       "emmet_ls",
  --       "eslint",
  --       "angularls",
  --     },
  --     -- auto install configured servers
  --     automatic_installation = true,
  --   })
  --
  --   mason_tool_installer.setup({
  --     ensure_installed = {
  --       "prettier",
  --       "stylua",
  --       "eslint_d",
  --     },
  --   })
  -- end,
}
