[colors]
foreground="#E4E3DD"
background="#272229"
cursor_bg="#E4E3DD"
cursor_border="#E4E3DD"
cursor_fg="#272229"
selection_bg="#49404D"
selection_fg="#E4E3DD"
split="#F5EBA3"
compose_cursor="#EDDC5A"
scrollbar_thumb="#49404D"

ansi = [
  "#231F25",
  "#C6362C",
  '#7CAE50',
  '#D1BC18',
  '#64A4B0',
  '#BFB04A',
  '#745869',
  '#A4A28E',
]

brights = [
  '#322C35',
  "#DA6058",
  '#96BF73',
  '#F1E37E',
  '#A1C8CE',
  '#D5CB86',
  '#B096A6',
  '#E4E3DD',
]

[colors.tab_bar]
  background='#322C35'

[colors.tab_bar.active_tab]
  bg_color='#EDDC5A'
  fg_color='#322C35'
  intensity='Bold'

[colors.tab_bar.inactive_tab]
  bg_color='#6B5D70'
  fg_color='#DAC2D1'
[colors.tab_bar.inactive_tab_hover]
  bg_color='#A6983A'
  fg_color='#322C35'

[colors.tab_bar.new_tab]
  bg_color='#49404D'
  fg_color='#B096A6'
[colors.tab_bar.new_tab_hover]
  bg_color='#A6983A'
  fg_color='#322C35'

[metadata]
aliases = []
author = "Dennis van den Berg (http://github.com/dlvandenberg/)"
name = "mountnugget"
