console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
version = 3
final_space = true

[palette]
  arylide = '#EDDC5A'
  ash = '#B6B5A4'
  asparagus = '#7CAE50'
  battleship = '#908D75'
  citrine = '#E9D439'
  citron = '#D5CB86'
  eggplant = '#745869'
  flax = '#F1E37E'
  gold = '#BFB04A'
  indian = '#DA6058'
  jasper = '#D75147'
  khaki = '#A4A28E'
  light_blue = '#A1C8CE'
  moonstone = '#64A4B0'
  mountbatten = '#8C697E'
  munsell = '#5396A2'
  olivine = '#8CB865'
  persian = '#C6362C'
  pink = '#9F7F92'
  pistachio = '#96BF73'
  platinum = '#E4E3DD'
  poppy = '#D34136'
  rose = '#DAC2D1'
  satin = '#A6983A'
  sky = '#86B8C1'
  teal = '#467E86'
  terminal_bg = '#272229'
  timberwolf = '#C9C8BB'
  vanilla = '#F5EBA3'
  white_smoke = '#F6F6F4'

[secondary_prompt]
  template = '➜ '
  foreground = 'p:gold'
  background = 'transparent'

[transient_prompt]
  template = '➜ '
  foreground = 'p:gold'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}} '
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = 'p:moonstone'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = '~'
      style = 'mixed'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = 'p:khaki'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:khaki{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:sky{{ end }}', '{{ if gt .Ahead 0 }}p:munsell{{ end }}', '{{ if gt .Behind 0 }}p:moonstone{{ end }}']

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = ' '
    foreground = 'p:poppy'
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:pistachio'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'ﳑ {{ .Full}} '
    foreground = 'p:sky'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '</> {{ .FormattedMs }} '
    foreground = 'p:mountbatten'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .CurrentDate | date .Format }}'
    foreground = 'p:rose'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    foreground = 'p:arylide'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
