console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'
version = 3
final_space = true

[palette]
  base       = '#191724'
  surface    = '#1f1d2e'
  overlay    = '#26233a'
  muted      = '#6e6a86'
  subtle     = '#908caa'
  text       = '#e0def4'
  love       = '#eb6f92'
  gold       = '#f6c177'
  rose       = '#ebbcba'
  pine       = '#31748f'
  foam       = '#9ccfd8'
  iris       = '#c4a7e7'
  highlight  = '#524f67'
  highlight_med = '#403d52'
  highlight_low = '#2a273f'
  white_smoke = '#e0def4'
  terminal_bg = '#191724'

[secondary_prompt]
  template = '➜ '
  foreground = 'p:gold'
  background = 'transparent'

[transient_prompt]
  template = '➜ '
  foreground = 'p:gold'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}} '
    type = 'os'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = 'p:foam'
    type = 'path'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = '~'
      style = 'mixed'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = 'p:subtle'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:rose{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:foam{{ end }}', '{{ if gt .Ahead 0 }}p:iris{{ end }}', '{{ if gt .Behind 0 }}p:pine{{ end }}']
    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = ' '
    foreground = 'p:love'
    type = 'status'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:foam'
    type = 'node'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = 'ﳑ {{ .Full}} '
    foreground = 'p:pine'
    type = 'go'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '</> {{ .FormattedMs }} '
    foreground = 'p:muted'
    type = 'executiontime'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{ .CurrentDate | date .Format }}'
    foreground = 'p:iris'
    type = 'time'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    foreground = 'p:gold'
    type = 'text'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'

